server:
  port: 8001
  host: 0.0.0.0

db:
  host: pg-docker
  port: 5432
  user: pratik
  password: DB_PASS_ENV
  db_name: pratikdb

jwt:
  duration_minutes: 15
  refresh_duration_minutes: 15
  signing_algorithm: HS256
  signing_key_env: SIGNING_KEY_ENV